### ISSUE TITLE
Add base home content

### ISSUE THREAD

**Issue by Schiller-Stoff** [Schiller-Stoff/project-website#13]
###TODOs
- [x] add some logos
- [x] license
- [x] GAMS
- [x] UNi Graz
- [x] placeholder Uni Wien
- [x] placeholder Icarus
- [x] placeholder Go Digital??
- [x] placeholder more?

**Comment by Schiller-Stoff** [comment]
implemented
