### ISSUE TITLE
Handle all static pages via wordpress backend

### ISSUE THREAD

**Issue by Schiller-Stoff** [Schiller-Stoff/project-website#14]
### DESC
- as discussed last time all static pages will be rendered dynamically rendered via receiving a json response from the wp-backend.
- look up which data is returned by wordpress backend endpoints
-  [wordpress-reference](https://developer.wordpress.org/rest-api/reference/pages/)

### Some Endpoints
- [list pages](https://nampi.icar-us.eu/wp-json/wp/v2/pages)

### TODOs
- [x] add useWorpressPage hook
- [x] add wordpress transformer component
- [x] use component in static pages?
- [x] implement

**Comment by Schiller-Stoff** [comment]
implemented --> component is available
