### ISSUE TITLE
Update to new version of nampi-use-api

### ISSUE THREAD

**Issue by Schiller-Stoff** [Schiller-Stoff/project-website#15]
### DESC
- impl of nampi-use-api has changed with breaking changes needs to be updated
- breaking changes need to be resolved

### TODOs
- [x] install new version
- [x] base correction of type errors etc. so that app does not fail
- [x] repair persons list etc.

**Comment by Schiller-Stoff** [comment]
implemented
