### ISSUE TITLE
Build base navigation architecture according to new material

### ISSUE THREAD

**Issue by Schiller-Stoff** [Schiller-Stoff/project-website#18]
### TODOs
- [x] add link to NAMPI data page to nav
- [x] add sources (dropdown?)
- [x] add sample links to dropdown
- [x] add more todos

**Comment by Schiller-Stoff** [comment]
implemented
