### ISSUE TITLE
Add project about

### ISSUE THREAD

**Issue by Schiller-Stoff** [Schiller-Stoff/project-website#4]
### TODOs
- [x] base implement about (add page component + page)
- [x] handle app routes via constant
- [x] find out necessary stuff according to gams pages / prodomo page / project files
- [x] add /about route to application
- [x] call correct page component
- [x] provide content via react intl (but just demo text)
- [x] implement

**Comment by Schiller-Stoff** [comment]
implemented
